### ISSUE TITLE
Failed to activate the github-issues package

### ISSUE THREAD

**Issue by vipintm** [r24y/github-issues#35]
Cannot read property 'match' of null

**Atom Version**: 1.7.2
**System**: Ubuntu 14.04.4
**Thrown From**: [github-issues](https://github.com/baconscript/github-issues) package, v0.7.0
### Stack Trace

Failed to activate the github-issues package

```
At Cannot read property 'match' of null

TypeError: Cannot read property 'match' of null
    at isGitHubRepo (/home/vipintm/.atom/packages/github-issues/index.coffee:17:21)
    at fetchIssues (/home/vipintm/.atom/packages/github-issues/index.coffee:27:21)
    at Object.module.exports.activate (/home/vipintm/.atom/packages/github-issues/index.coffee:47:5)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
gcc-make-run, v0.2.6
github-issues, v0.7.0
imdone-atom-github, v0.1.11
latexer, v0.3.0
linter, v1.11.4
markdown-assistant, v0.1.0
minimap, v4.22.1

# Dev
No dev packages
```

**Comment by mschinis** [comment]
I very recently started getting this as well.

**Comment by r24y** [comment]
Sorry to let this linger for so long, but try your luck with `v0.8.0`. I was pretty thorough this time so I don't think you'll see that issue. Let me know if it recurs, though.
